version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_commerce
    ports:
      - "37310:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "37320:5672"
      - "37321:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:alpine
    ports:
      - "37330:6379"
      - 
  api:
    build:
      context: ./MiniCommerce.Api
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
      - redis
    ports:
      - "37300:443"
      - "37301:80"
    volumes:
      - ./logs/api:/app/log

  processor:
    build:
      context: ./MiniCommerce.Processor
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
      - redis
    volumes:
      - ./logs/processor:/app/log

volumes:
  pgdata:
  
